android_resource(
  name = 'res',
  res = 'res',
  package = 'com.ryanendacott.starterapp',
  visibility = [
    '//apps/starterapp:',
  ],
)

project_config(
  src_target = ':res',
  src_roots = None,
)
