android_binary(
  name = 'starterapp',
  manifest = 'AndroidManifest.xml',
  target = 'Google Inc.:Google APIs:19',
  keystore = ':debug_keystore',
  deps = [
    '//java/com/ryanendacott/starterapp/application:application',
    '//java/com/ryanendacott/starterapp/main:main',
    '//res/com/ryanendacott/starterapp/application:res',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)

project_config(
  src_target = ':starterapp',
)
