android_library_with_dagger(
  name = 'application',
  srcs = glob(['*.java']),
  deps = [
    '//java/com/ryanendacott/starterapp/inject:inject',
    '//java/com/ryanendacott/starterapp/main:main',
  ],
  visibility = [ 'PUBLIC' ],
)

project_config(
  src_target = ':application',
)
