android_library_with_dagger(
  name = 'main',
  srcs = glob(['*.java']),
  deps = [
    '//java/com/ryanendacott/starterapp/inject:inject',
    '//res/com/ryanendacott/starterapp/main:res',
  ],
  visibility = [ 'PUBLIC' ],
)

project_config(
  src_target = ':main',
)

